services:
  docker-dind:
    image: docker:27-dind
    user: root
    privileged: true
    ports:
      - "2376:2376"
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    networks:
      jenkins:
        aliases:
          - docker

  jenkins:
    image: jenkins/jenkins:2.527-jdk21
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_docker_certs:/certs/client:ro
      - /usr/bin/docker:/usr/bin/docker
    environment:
      DOCKER_HOST: "tcp://docker-dind:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"
    depends_on:
      - docker-dind
    networks:
      - jenkins

volumes:
  jenkins_data:
  jenkins_docker_certs:
  
networks:
  jenkins:
    driver: bridge